require('dotenv').config();
const express=require('express'); const cors=require('cors'); const path=require('path'); const fs=require('fs'); const multer=require('multer'); const bcrypt=require('bcryptjs'); const jwt=require('jsonwebtoken'); const rateLimit=require('express-rate-limit');
const Database=require('better-sqlite3'); const Stripe=require('stripe');
const app=express(); const PORT=Number(process.env.PORT||3000); const ROOT=path.resolve(__dirname,'../..');
const dataDir=path.resolve(ROOT,process.env.DATABASE_PATH||'./data/mountpeak.db'); fs.mkdirSync(path.dirname(dataDir),{recursive:true}); const uploadDir=path.resolve(ROOT,process.env.UPLOAD_DIR||'./data/uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const db=new Database(dataDir); db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS candidates(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,us_location TEXT NOT NULL,education TEXT,specialization TEXT,total_experience TEXT,relevant_experience TEXT,job_title TEXT,preferred_role TEXT,preferred_location TEXT,visa_status TEXT,skills TEXT,service TEXT,notes TEXT,resume_path TEXT,resume_original_name TEXT,status TEXT DEFAULT 'New',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS contact_inquiries(id INTEGER PRIMARY KEY AUTOINCREMENT,full_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,resume_path TEXT,resume_original_name TEXT,status TEXT DEFAULT 'New',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,candidate_id INTEGER,transaction_id TEXT UNIQUE,provider TEXT NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL,status TEXT NOT NULL,payment_method TEXT,provider_order_id TEXT,metadata TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(candidate_id) REFERENCES candidates(id));CREATE TABLE IF NOT EXISTS ai_conversations(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,message TEXT NOT NULL,reply TEXT NOT NULL,action TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,action TEXT,entity TEXT,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
const adminEmail=process.env.ADMIN_EMAIL, adminPassword=process.env.ADMIN_PASSWORD; if(adminEmail&&adminPassword&&!db.prepare('SELECT 1 FROM admins WHERE email=?').get(adminEmail)){db.prepare('INSERT INTO admins(email,password_hash) VALUES(?,?)').run(adminEmail,bcrypt.hashSync(adminPassword,12));}
app.use(cors({origin:true})); app.use(express.json({limit:'1mb'})); app.use(express.urlencoded({extended:true})); app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true,legacyHeaders:false}));
const storage=multer.diskStorage({destination:(_,__,cb)=>cb(null,uploadDir),filename:(_,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase(); cb(null,`${Date.now()}-${Math.random().toString(36).slice(2)}${ext}`)}}); const upload=multer({storage,limits:{fileSize:8*1024*1024},fileFilter:(_,file,cb)=>cb(null,/^\.(pdf|doc|docx)$/i.test(path.extname(file.originalname)))});
function tokenFor(admin){return jwt.sign({sub:admin.id,email:admin.email,role:'admin'},process.env.JWT_SECRET||'dev-only-secret',{expiresIn:'8h'});} function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Authentication required.'});req.admin=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-only-secret');next()}catch{return res.status(401).json({message:'Invalid or expired session.'})}}
app.get('/api/health',(_,res)=>res.json({ok:true,service:'MountPeak Group API'}));
app.post('/api/admin/login',async(req,res)=>{const {email,password}=req.body||{};const admin=db.prepare('SELECT * FROM admins WHERE email=?').get(email);if(!admin||!bcrypt.compareSync(password||'',admin.password_hash))return res.status(401).json({message:'Invalid credentials.'});res.json({token:tokenFor(admin),admin:{id:admin.id,email:admin.email}})});
app.post('/api/candidates',upload.single('Resume'),(req,res)=>{try{const b=req.body; if(!b['Full Name']||!b.Email||!b.Phone||!b['US Location']||!b['Visa Status']||!req.file) return res.status(400).json({message:'Please complete all required fields and upload a PDF/DOC/DOCX resume.'});const r=db.prepare(`INSERT INTO candidates(full_name,email,phone,us_location,education,specialization,total_experience,relevant_experience,job_title,preferred_role,preferred_location,visa_status,skills,service,notes,resume_path,resume_original_name) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(b['Full Name'],b.Email,b.Phone,b['US Location'],b.Education||'',b.Specialization||'',b['Total Experience']||'',b['Relevant Experience']||'',b['Job Title']||'',b['Preferred Role']||'',b['Preferred Location']||'',b['Visa Status'],b.Skills||'',b.Service||'',b.Notes||'',req.file.path,req.file.originalname);res.status(201).json({message:'Your profile has been submitted successfully.',candidateId:r.lastInsertRowid})}catch(e){res.status(500).json({message:'Unable to save the profile.'})}});
app.post('/api/contact',upload.single('Resume'),(req,res)=>{try{const b=req.body;if(!b['Full Name']||!b.Phone||!b.Email||!req.file)return res.status(400).json({message:'Please provide your name, phone, email and resume.'});const r=db.prepare(`INSERT INTO contact_inquiries(full_name,phone,email,resume_path,resume_original_name) VALUES(?,?,?,?,?)`).run(b['Full Name'],b.Phone,b.Email,req.file.path,req.file.originalname);res.status(201).json({message:'Thank you. Your inquiry has been received.',inquiryId:r.lastInsertRowid})}catch{res.status(500).json({message:'Unable to save your inquiry.'})}});
app.get('/api/admin/dashboard',auth,(req,res)=>{const count=t=>db.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n;res.json({candidates:count('candidates'),contacts:count('contact_inquiries'),payments:count('payments'),paidAmount:db.prepare("SELECT COALESCE(SUM(amount),0) n FROM payments WHERE status='PAID'").get().n/100})});
app.get('/api/admin/candidates',auth,(req,res)=>{const rows=db.prepare('SELECT id,full_name,email,phone,us_location,job_title,preferred_role,visa_status,status,created_at FROM candidates ORDER BY id DESC').all();res.json(rows)});
app.get('/api/admin/contacts',auth,(req,res)=>res.json(db.prepare('SELECT id,full_name,phone,email,status,created_at FROM contact_inquiries ORDER BY id DESC').all()));
app.get('/api/admin/payments',auth,(req,res)=>res.json(db.prepare(`SELECT p.*,c.full_name,c.email FROM payments p LEFT JOIN candidates c ON c.id=p.candidate_id ORDER BY p.id DESC`).all()));
app.patch('/api/admin/candidates/:id/status',auth,(req,res)=>{const allowed=['New','Screening','Shortlisted','Interview','Selected','Rejected','Withdrawn','On Hold'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status.'});db.prepare('UPDATE candidates SET status=? WHERE id=?').run(req.body.status,req.params.id);db.prepare('INSERT INTO audit_logs(admin_id,action,entity,entity_id) VALUES(?,?,?,?)').run(req.admin.sub,'status_update','candidate',req.params.id);res.json({ok:true})});

const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
app.post('/api/payments/stripe/create',async(req,res)=>{try{if(!stripe)return res.status(503).json({message:'Card payments are not configured yet. Add STRIPE_SECRET_KEY to the server environment.'});const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({message:'Invalid amount.'});const session=await stripe.checkout.sessions.create({mode:'payment',line_items:[{price_data:{currency:(req.body.currency||'USD').toLowerCase(),product_data:{name:'MountPeak Group Payment'},unit_amount:Math.round(amount*100)},quantity:1}],success_url:`${process.env.FRONTEND_URL||'http://localhost:3000'}/?payment=success`,cancel_url:`${process.env.FRONTEND_URL||'http://localhost:3000'}/?payment=cancelled`,metadata:{source:'mountpeak-group'}});db.prepare(`INSERT INTO payments(transaction_id,provider,amount,currency,status,payment_method,provider_order_id,metadata) VALUES(?,?,?,?,?,?,?,?)`).run(`STRIPE-${session.id}`, 'stripe',Math.round(amount*100),(req.body.currency||'USD').toUpperCase(),'PENDING','card',session.id,JSON.stringify({checkoutSessionId:session.id}));res.json({checkoutUrl:session.url})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/payments/stripe/webhook',express.raw({type:'application/json'}),async(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).end();try{const event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);if(event.type==='checkout.session.completed'){const s=event.data.object;db.prepare("UPDATE payments SET status='PAID',updated_at=CURRENT_TIMESTAMP WHERE provider_order_id=?").run(s.id)}res.json({received:true})}catch(e){res.status(400).send(`Webhook Error: ${e.message}`)}});

async function paypalToken(){const auth=Buffer.from(`${process.env.PAYPAL_CLIENT_ID}:${process.env.PAYPAL_CLIENT_SECRET}`).toString('base64');const r=await fetch(`${process.env.PAYPAL_BASE_URL||'https://api-m.sandbox.paypal.com'}/v1/oauth2/token`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'PayPal authentication failed');return d.access_token;}
app.post('/api/payments/paypal/create',async(req,res)=>{try{if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)return res.status(503).json({message:'PayPal is not configured yet. Add PayPal credentials to the server environment.'});const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({message:'Invalid amount.'});const t=await paypalToken();const base=process.env.PAYPAL_BASE_URL||'https://api-m.sandbox.paypal.com';const r=await fetch(`${base}/v2/checkout/orders`,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({intent:'CAPTURE',purchase_units:[{amount:{currency_code:req.body.currency||'USD',value:amount.toFixed(2)}}],application_context:{return_url:`${process.env.FRONTEND_URL||'http://localhost:3000'}/?paypal_return=1`,cancel_url:`${process.env.FRONTEND_URL||'http://localhost:3000'}/?payment=cancelled`}})});const o=await r.json();if(!r.ok)throw new Error(o.message||'PayPal order creation failed');const link=o.links?.find(x=>x.rel==='approve')?.href;db.prepare(`INSERT INTO payments(transaction_id,provider,amount,currency,status,payment_method,provider_order_id,metadata) VALUES(?,?,?,?,?,?,?,?)`).run(`PAYPAL-${o.id}`,'paypal',Math.round(amount*100),(req.body.currency||'USD').toUpperCase(),'PENDING','paypal',o.id,JSON.stringify({orderId:o.id}));res.json({approvalUrl:link,orderId:o.id})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/payments/paypal/capture',async(req,res)=>{try{if(!process.env.PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)return res.status(503).json({message:'PayPal is not configured.'});const t=await paypalToken();const base=process.env.PAYPAL_BASE_URL||'https://api-m.sandbox.paypal.com';const r=await fetch(`${base}/v2/checkout/orders/${req.body.orderId}/capture`,{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'}});const o=await r.json();if(!r.ok)throw new Error(o.message||'PayPal capture failed');const status=o.status==='COMPLETED'?'PAID':'PENDING';db.prepare('UPDATE payments SET status=?,updated_at=CURRENT_TIMESTAMP WHERE provider_order_id=?').run(status,req.body.orderId);res.json({status,orderId:req.body.orderId})}catch(e){res.status(500).json({message:e.message})}});

app.post('/api/ai/navigation',async(req,res)=>{const message=String(req.body.message||'').trim();if(!message)return res.status(400).json({message:'Message required.'});let action=null,reply='';const m=message.toLowerCase();if(/pay|payment|card|paypal|debit|credit/.test(m)){action='payment';reply='I can take you to the secure payment page. Enter the amount provided by the MountPeak Group team and choose PayPal or credit/debit card checkout.'}else if(/resume|cv|candidate|apply|job|career|profile/.test(m)){action='profile';reply='I can take you to Submit Your Profile, where you can provide your professional details and securely upload your resume.'}else if(/employer|hire|hiring|talent|recruit/.test(m)){action='employers';reply='I can take you to the For Employers section for recruitment and talent-support information.'}else if(/service|what do you|offer/.test(m)){action='services';reply='MountPeak Group provides US IT and non-IT staffing, resume and career support, interview support, STEM OPT candidate support, and employer talent solutions.'}else if(/contact|email|phone|talk/.test(m)){action='contact';reply='I can take you to Contact Us so you can send your details to the MountPeak Group team.'}else{reply='I can help with candidates, employers, services, contact, and payments. Try “I want to submit my resume” or “I want to make a payment.”'}db.prepare('INSERT INTO ai_conversations(session_id,message,reply,action) VALUES(?,?,?,?,?)').run(String(req.body.sessionId||'web'),'message',reply,action);res.json({reply,action})});

// Serve frontend in the same deployment. For production, put the API behind HTTPS and use a managed database/storage service.
app.use(express.static(path.join(ROOT,'frontend'))); app.get('*',(req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({message:'API route not found'});res.sendFile(path.join(ROOT,'frontend','index.html'))});
app.listen(PORT,()=>console.log(`MountPeak Group running on http://localhost:${PORT}`));
